### PR TITLE
Create ubiquity-research-korea.md

### LINKED ISSUE #70: Create Ubiquity Research Korea
As discussed in private channels, we're looking to create a local entity.

### PR DESCRIPTION
**Pull request by diamondnegroni**
Resolves #70

### CODE REVIEW

**Review by 0x4007 — CHANGES_REQUESTED** [review]
This deliverable will be more useful to post all of the official information/documentation for the entity so that we can use it for future purposes. 

It appears that you wrote down a project proposal instead, which should be done in the GitHub issue specification instead.

**Comment by diamondnegroni** [comment]
Hum I'm not sure if it's a good idea to upload all the official documents because they're private informatoin that shouldn't be floating around the web especially the entity is LLC....

**Comment by 0x4007** [comment]
Sergey had similar concerns about the card issuance related documents. I don't know what the details entail but I'm not expecting an issue with posting things publicly. However, because I don't know exactly what the contents are, we have two options:

We can either make a private repository, or you can post a Google Drive link for now (be sure to drop in the documents into our Google Drive!)

**Comment by diamondnegroni** [comment]
As of February 18, a bank made an office visit on February 16, asking for contracts to verify the legitimacy of our business entity. 
I inquired with a lawyer about the difficulty of banking as a newly established LLC, and it appears this particular bank branch is quite conservative and uncooperative. I am considering two alternative strategies:
1. Investigate opening accounts with different banks in Gyeonggi-do.
2. Contemplate relocating the office to Seoul, where banks are known to be more accommodating and practical for business dealings.

**Comment by diamondnegroni** [comment]
As of 20th of Feb, I'm visiting one more bank in Gyeonggi-do before I try to relocate the bank in Seoul.

**Comment by diamondnegroni** [comment]
Another bank in Gyeonggi-do has requested the same contract, prompting me to change the office location to Seoul for address purposes.

Here are the steps going-forward:

1. Deregister the office in Gyeonggi-do (2-3 days).
2. Secure a new office space in Seoul for entity address registration (1 day).
3. Update the entity's address with the Title Office in both Gyeonggi-do and Seoul (2-3 days).
4. Activate the account by visiting the bank in Seoul (2-3 days).

**Comment by 0x4007** [comment]
Okay let me know if there's anything I can help with. Thanks for the update!

**Comment by diamondnegroni** [comment]
The Title registration is completed so I will visit banks in Seoul to finish the logitics

**Comment by 0x4007** [comment]
How long do you think it would take from here?

**Comment by diamondnegroni** [comment]
The transfer of of ownership will take 3-5 biz days so mid next week !

**Pull request closed without merging**
