### PR TITLE
feat: add pitchdeck content

### LINKED ISSUE #60: Content
create outline for content narrative. 
create content google slide deliverable. 
target audience is business decision makers as opposed to mid-level operators.

### PR DESCRIPTION
**Pull request by 0x4007**
Resolves #60

### CODE REVIEW

**Comment by 0x4007** [comment]
For your information @Hodlatoor you can open the context menu (three dots) and view the file as a rendered document inside of the "Files changed" view. 

Example [link](https://github.com/ubiquity/business-development/blob/c6a83962d993ef40ee2fa49498fed2b60d1bca3c/partners/b2b-pitchdeck-content.md).

**Comment by Hodlatoor** [comment]
@pavlovcik yes, content is there but the slide images / formatting (the slides) are not. are you working on that or are we using what I put together?

**Comment by 0x4007** [comment]
I don't have time to work on it this next few days so we can go with your version if you're in a rush. 

It's important to remember that this task is only for content. And to be honest I would have requested changes on the content because this is an article that could be distributed on a blog or publication; not a pitchdeck. 

It's a common mistake for people to take articles and encode them as pitchdecks. 

The pitchdecks that convert are extremely concise because they are presentation collateral, not books.

**Comment by 0x4007** [comment]
You need to approve this pull request before it can be merged.

**Pull request merged**
