### PR TITLE
Chore: find 40+ bounty boards

### PR DESCRIPTION
**Pull request by diamondnegroni**
Resolves # #27

### CODE REVIEW

**Comment by 0x4007** [comment]
You guys @sergfeldman @Draeieg handled recruiting before. Do you have any remarks?

**Review by 0x4007 — CHANGES_REQUESTED** [review]
We can't use the telegram chats because usually they ban for recruiting/spam. 

There's also some job working sites on there like Toptal and upwork which I'm not sure if workers would be comfortable to handle payments off of those platforms. 

We need crypto native sites because contributors need familiarity with crypto to use our system.

**Comment by Draeieg** [comment]
> You guys @sergfeldman @Draeieg handled recruiting before. Do you have any remarks?
> 
> We can't use the telegram chats because usually they ban for recruiting/spam. 

There are traditional freelancer sites there, We'd have to set up fiat payments to use them

Also, a chunk of bug/security bounty sites there, which we technically don't have a process for yet

It's insanely dope that someone actually came and solved this, tho

**Comment by diamondnegroni** [comment]
@pavlovcik The telegrams that I included in the list are ads friendly because they're community or muiti-national crypto events so people share information.
@Draeieg yes I was expanding the boundaries out of crypto because what I have on the list is all-inclusive for crypto-native bug bounty hunts platorms. 
After spending a day of research, this is all I have.

**Comment by 0x4007** [comment]
@sergfeldman I'll let you lead this review as you probably know best on this topic.

**Comment by sergfeldman** [comment]
@diamondnegroni Hey, thank you for the findings!

The task of finding relevant freelance sites is not a small one.
40 provided sites as a result of 1-day research is fine.
I found interesting new Telegram channels that allow posting bounties.

At the same time, we should mind actionable steps that will be performed after the research.
As I understand, the actionable step will be to publish DevPool tasks on these freelance sites and measure performance.

To achieve this goal, it would be good to rebuild the list.
1) Most importantly, please add relevant crypto-friendly freelance sites.

- Please clarify have you checked resources in Sovs?
https://sovs.notion.site/Jobs-7062a940fb8548edb075171881a5d2b9

- Additionally, please add sites like
https://app.dework.xyz/
https://laborx.com/

- Please make sure that it is possible to publish bounties on the sites in the list.
For example, I have not found how to post DevPool bounties here 
https://www.cryptoknowmics.com/bounty

2) Less importantly, it would be good to group sites by type.
It will help if some site types have limitations in posting DevPool tasks (for example, bug bounties sites).

**Comment by 0x4007** [comment]
> Do you have any updates @sergfeldman? If you would like to release the bounty back to the DevPool, please comment `/unassign`
> Last activity time: Mon Jul 10 2023 13:27:48 GMT+0000 (Coordinated Universal Time)

This is hilarious, I didn't realize that the bot follows up on assignees for pull requests.

**Comment by diamondnegroni** [comment]
@sergfeldman @pavlovcik I updated the request based on the requset

**Comment by sergfeldman** [comment]
### Regarding the PR
This list of sites provides the ability to start experiments with posting DevPool bounties. 

Although, there are still some issues. For example, 
https://jobs.multicoin.capital/jobs is not a relevant site for posting DevPool bounties.
https://www.fiverr.com/ is not correctly classified as a Blockchain job posting.

There are two different files in this PR:
1) bounty-boards/50-bounty-boards.md
https://github.com/ubiquity/business-development/pull/42/files#diff-44d866af430560fb16379d36a3e50acfa4576bfcfddcd02c42930663c773289c
2) Proposal for Ethcon Korea 2023 Sponsorship .md
https://github.com/ubiquity/business-development/pull/42/files#diff-0a6b3203ffad612a92fa9464f05130e9ed098324f035e7462cfcd98e09c5e409
@diamondnegroni In the future, please provide a separate PR for each update.

### Proposed decision 
The task to find sites for posting DevPool bounties is pretty large, but this particular bounty is small.

This is the 1st bounty made by @diamondnegroni
Please, inform us how many hours you spent on this bounty so that we use this info in the future.

@pavlovcik I propose to consider this bounty as completed.
The task of collecting more sites may appear in the future.

**Comment by diamondnegroni** [comment]
Thank you for the feedback @sergfeldman. 
I spent about good 5 hours to search, verify, and update the list.

**Comment by sergfeldman** [comment]
> Thank you for the feedback @sergfeldman. I spent about good 5 hours to search, verify, and update the list.

@diamondnegroni Thank you for completing the task! 

Please clarify, are these 5 hours total spent for the whole task including the initial search and updates according to the comments?
Or are these 5 hours spent updating according to my last comment?

It is desirable to understand how much it took to complete this task as a whole.

**Comment by diamondnegroni** [comment]
About 3 hours for the initial search and listing
About 2 hours for the updating the list based on the request

**Comment by sergfeldman** [comment]
> About 3 hours for the initial search and listing About 2 hours for the updating the list based on the request

@diamondnegroni Thank you for the information.

**Pull request merged**
